monolog:
    channels:
        - deprecation # Deprecations are logged in the dedicated "deprecation" channel when it exists
    handlers:
        deprecation:
            type: rotating_file
            channels: [ deprecation ]
            path: "%kernel.logs_dir%/deprecations/%kernel.environment%.deprecations.log"
            max_files: 2

when@dev:
    monolog:
        channels:
            - login
            - personal_data
            - user
            - relay
            - affiliation
            - sms
            - api
            - disk_capacity
        handlers:
            main:
                type: fingers_crossed
                action_level: error
                handler: nested
                excluded_http_codes: [ 404, 405 ]
                channels: [ "!event" ]
            nested:
                type: stream
                path: "%kernel.logs_dir%/%kernel.environment%.log"
                level: debug
            activity:
                level: debug
                type: stream
                path: '%kernel.logs_dir%/activity_dev/login.log'
                channels: [ 'login' ]
            personal_data:
                level: debug
                type: stream
                path: '%kernel.logs_dir%/activity_dev/personal_data.log'
                channels: [ 'personal_data' ]
            user:
                level: debug
                type: stream
                path: '%kernel.logs_dir%/activity_dev/user.log'
                channels: [ 'user' ]
            relay:
                level: debug
                type: stream
                path: '%kernel.logs_dir%/activity_dev/relay.log'
                channels: [ 'relay' ]
            affiliation:
                level: debug
                type: stream
                path: '%kernel.logs_dir%/activity_dev/affiliation.log'
                channels: [ 'affiliation' ]
            sms:
                level: debug
                type: stream
                path: '%kernel.logs_dir%/activity_dev/sms.log'
                channels: [ 'sms' ]
            api:
                level: debug
                type: stream
                path: '%kernel.logs_dir%/api_dev/v3.log'
                channels: [ 'api' ]
            disk_capacity:
                level: debug
                type: stream
                path: '%kernel.logs_dir%/monitoring/disk_capacity.log'
                channels: [ 'disk_capacity' ]
            console:
                type: console
                process_psr_3_messages: false
                channels: [ "!event", "!doctrine", "!console" ]

when@test:
    monolog:
        channels:
            - login
            - personal_data
            - user
            - relay
            - affiliation
            - api
            - disk_capacity
        handlers:
            main:
                type: fingers_crossed
                action_level: error
                handler: nested
                excluded_http_codes: [ 404, 405 ]
                channels: [ "!event" ]
            nested:
                type: stream
                path: "%kernel.logs_dir%/%kernel.environment%.log"
                level: debug
            activity:
                level: debug
                type: stream
                path: '%kernel.logs_dir%/activity_test/login.log'
                channels: [ 'login' ]
            personal_data:
                level: debug
                type: stream
                path: '%kernel.logs_dir%/activity_test/personal_data.log'
                channels: [ 'personal_data' ]
            user:
                level: debug
                type: stream
                path: '%kernel.logs_dir%/activity_test/user.log'
                channels: [ 'user' ]
            relay:
                level: debug
                type: stream
                path: '%kernel.logs_dir%/activity_test/relay.log'
                channels: [ 'relay' ]
            affiliation:
                level: debug
                type: stream
                path: '%kernel.logs_dir%/activity_test/affiliation.log'
                channels: [ 'affiliation' ]
            api:
                level: debug
                type: stream
                path: '%kernel.logs_dir%/api_test/v3.log'
                channels: [ 'api' ]
            disk_capacity:
                level: debug
                type: stream
                path: '%kernel.logs_dir%/monitoring/disk_capacity.log'
                channels: [ 'disk_capacity' ]

when@preprod:
    monolog:
        channels:
            - login
            - personal_data
            - user
            - relay
            - affiliation
            - api
            - sms
            - disk_capacity
        handlers:
            main:
                type: fingers_crossed
                action_level: error
                handler: nested
                excluded_http_codes: [ 404, 405 ]
                buffer_size: 50 # How many messages should be saved? Prevent memory leaks
            nested:
                type: rotating_file
                path: "%kernel.logs_dir%/%kernel.environment%.log"
                level: debug
                max_files: 10
            console:
                type: console
                process_psr_3_messages: false
                channels: [ "!event", "!doctrine" ]
            activity:
                level: debug
                type: rotating_file
                path: '%kernel.logs_dir%/activity_preprod/login/login.log'
                channels: [ 'login' ]
                max_files: 365
            personal_data:
                level: debug
                type: rotating_file
                path: '%kernel.logs_dir%/activity_preprod/personal_data/personal_data.log'
                channels: [ 'personal_data' ]
                max_files: 365
            user:
                level: debug
                type: rotating_file
                path: '%kernel.logs_dir%/activity_preprod/user/user.log'
                channels: [ 'user' ]
                max_files: 365
            relay:
                level: debug
                type: rotating_file
                path: '%kernel.logs_dir%/activity_preprod/relay/relay.log'
                channels: [ 'relay' ]
                max_files: 365
            affiliation:
                level: debug
                type: rotating_file
                path: '%kernel.logs_dir%/activity_preprod/affiliation/affiliation.log'
                channels: [ 'affiliation' ]
                max_files: 365
            api:
                level: debug
                type: rotating_file
                path: '%kernel.logs_dir%/api_preprod/v3.log'
                channels: [ 'api' ]
                max_files: 10
            sms:
                level: debug
                type: stream
                path: '%kernel.logs_dir%/activity_preprod/sms.log'
                channels: [ 'sms' ]
            disk_capacity:
                level: debug
                type: stream
                path: '%kernel.logs_dir%/monitoring_preprod/disk_capacity.log'
                channels: [ 'disk_capacity' ]

when@prod:
    monolog:
        channels:
            - login
            - personal_data
            - user
            - relay
            - affiliation
            - api
            - disk_capacity
        handlers:
            main:
                type: fingers_crossed
                action_level: error
                handler: nested
                excluded_http_codes: [ 404, 405 ]
                buffer_size: 50 # How many messages should be saved? Prevent memory leaks
            nested:
                type: rotating_file
                path: "%kernel.logs_dir%/%kernel.environment%.log"
                level: debug
                max_files: 10
            console:
                type: console
                process_psr_3_messages: false
                channels: [ "!event", "!doctrine" ]
            activity:
                level: debug
                type: rotating_file
                path: '%kernel.logs_dir%/activity/login/login.log'
                channels: [ 'login' ]
                max_files: 365
            personal_data:
                level: debug
                type: rotating_file
                path: '%kernel.logs_dir%/activity/personal_data/personal_data.log'
                channels: [ 'personal_data' ]
                max_files: 365
            user:
                level: debug
                type: rotating_file
                path: '%kernel.logs_dir%/activity/user/user.log'
                channels: [ 'user' ]
                max_files: 365
            relay:
                level: debug
                type: rotating_file
                path: '%kernel.logs_dir%/activity/relay/relay.log'
                channels: [ 'relay' ]
                max_files: 365
            affiliation:
                level: debug
                type: rotating_file
                path: '%kernel.logs_dir%/activity/affiliation/affiliation.log'
                channels: [ 'affiliation' ]
                max_files: 365
            api:
                level: debug
                type: rotating_file
                path: '%kernel.logs_dir%/api/v3.log'
                channels: [ 'api' ]
                max_files: 10
            disk_capacity:
                level: debug
                type: stream
                path: '%kernel.logs_dir%/monitoring/disk_capacity.log'
                channels: [ 'disk_capacity' ]

