monolog:
    channels:
        - deprecation # Deprecations are logged in the dedicated "deprecation" channel when it exists
    handlers:
        deprecation:
            type: rotating_file
            channels: [ deprecation ]
            path: "%kernel.logs_dir%/deprecations/%kernel.environment%.deprecations.log"
            max_files: 30

when@dev:
    monolog:
        channels:
            - login
            - personal_data
            - user
            - relay
            - affiliation
            - sms
            - api
        handlers:
            main:
                type: fingers_crossed
                action_level: error
                handler: nested
                excluded_http_codes: [ 404, 405 ]
                channels: [ "!event" ]
            nested:
                type: stream
                path: "%kernel.logs_dir%/%kernel.environment%.log"
                level: debug
            activity:
                level: debug
                type: stream
                path: '%kernel.logs_dir%/activity_dev/login.log'
                channels: [ 'login' ]
            personal_data:
                level: debug
                type: stream
                path: '%kernel.logs_dir%/activity_dev/personal_data.log'
                channels: [ 'personal_data' ]
            user:
                level: debug
                type: stream
                path: '%kernel.logs_dir%/activity_dev/user.log'
                channels: [ 'user' ]
            relay:
                level: debug
                type: stream
                path: '%kernel.logs_dir%/activity_dev/relay.log'
                channels: [ 'relay' ]
            affiliation:
                level: debug
                type: stream
                path: '%kernel.logs_dir%/activity_dev/affiliation.log'
                channels: [ 'affiliation' ]
            sms:
                level: debug
                type: stream
                path: '%kernel.logs_dir%/activity_dev/sms.log'
                channels: [ 'sms' ]
            api:
                level: debug
                type: stream
                path: '%kernel.logs_dir%/api_dev/v3.log'
                channels: [ 'api' ]
            console:
                type: console
                process_psr_3_messages: false
                channels: [ "!event", "!doctrine", "!console" ]

when@test:
    monolog:
        channels:
            - login
            - personal_data
            - user
            - relay
            - affiliation
            - api
        handlers:
            main:
                type: fingers_crossed
                action_level: error
                handler: nested
                excluded_http_codes: [ 404, 405 ]
                channels: [ "!event" ]
            nested:
                type: stream
                path: "%kernel.logs_dir%/%kernel.environment%.log"
                level: debug
            activity:
                level: debug
                type: stream
                path: '%kernel.logs_dir%/activity_test/login.log'
                channels: [ 'login' ]
            personal_data:
                level: debug
                type: stream
                path: '%kernel.logs_dir%/activity_test/personal_data.log'
                channels: [ 'personal_data' ]
            user:
                level: debug
                type: stream
                path: '%kernel.logs_dir%/activity_test/user.log'
                channels: [ 'user' ]
            relay:
                level: debug
                type: stream
                path: '%kernel.logs_dir%/activity_test/relay.log'
                channels: [ 'relay' ]
            affiliation:
                level: debug
                type: stream
                path: '%kernel.logs_dir%/activity_test/affiliation.log'
                channels: [ 'affiliation' ]
            api:
                level: debug
                type: stream
                path: '%kernel.logs_dir%/api_test/v3.log'
                channels: [ 'api' ]

when@preprod:
    monolog:
        channels:
            - sms
            - api
        handlers:
            sms:
                level: debug
                type: stream
                path: '%kernel.logs_dir%/activity_dev/sms.log'
                channels: [ 'sms' ]
            api:
                level: debug
                type: stream
                path: '%kernel.logs_dir%/api_preprod/v3.log'
                channels: [ 'api' ]

when@prod:
    monolog:
        channels:
            - login
            - personal_data
            - user
            - relay
            - affiliation
            - api
        handlers:
            main:
                type: fingers_crossed
                action_level: error
                handler: nested
                excluded_http_codes: [ 404, 405 ]
                buffer_size: 50 # How many messages should be saved? Prevent memory leaks
            nested:
                type: stream
                path: "%kernel.logs_dir%/%kernel.environment%.log"
                level: debug
            console:
                type: console
                process_psr_3_messages: false
                channels: [ "!event", "!doctrine" ]
            activity:
                level: debug
                type: stream
                path: '%kernel.logs_dir%/activity/login.log'
                channels: [ 'login' ]
            personal_data:
                level: debug
                type: stream
                path: '%kernel.logs_dir%/activity/personal_data.log'
                channels: [ 'personal_data' ]
            user:
                level: debug
                type: stream
                path: '%kernel.logs_dir%/activity/user.log'
                channels: [ 'user' ]
            relay:
                level: debug
                type: stream
                path: '%kernel.logs_dir%/activity/relay.log'
                channels: [ 'relay' ]
            affiliation:
                level: debug
                type: stream
                path: '%kernel.logs_dir%/activity/affiliation.log'
                channels: [ 'affiliation' ]
            api:
                level: debug
                type: stream
                path: '%kernel.logs_dir%/api/v3.log'
                channels: [ 'api' ]
