security:
    role_hierarchy:
        ROLE_MEMBRE: ROLE_BENEFICIAIRE
        ROLE_GESTIONNAIRE: ROLE_MEMBRE
        ROLE_ASSOCIATION: ROLE_MEMBRE
        ROLE_ADMIN: ROLE_BENEFICIAIRE
        ROLE_SUPER_ADMIN: ROLE_ADMIN

    # https://symfony.com/doc/current/security/experimental_authenticators.html
    enable_authenticator_manager: true
    # https://symfony.com/doc/current/security.html#registering-the-user-hashing-passwords
    password_hashers:
        # a hasher used in the past for some users
        legacy:
            algorithm: sha512
            encode_as_base64: false
            iterations: 1
        App\Entity\User:
            algorithm: auto
            migrate_from:
                - sha512
    # https://symfony.com/doc/current/security.html#loading-the-user-the-user-provider
    providers:
        user_provider:
            entity:
                class: App\Entity\User
    firewalls:
        dev:
            pattern: ^/(_(profiler|wdt)|css|images|js)/
            security: false
        api_token:
            pattern: ^/api/token$
            security: false
        api:
            pattern: ^/api
            security: true
            stateless: true
            oauth2: true
            login_link:
                check_route: login_link
                signature_properties: [ 'id' ]
                lifetime: 1800
                max_uses: 1
        rosalie:
            pattern: ^/appli/rosalie
            security: true
            stateless: true
            oauth2: true
        main:
            pattern: ^/
            provider: user_provider
            custom_authenticators:
                - App\Security\Authenticator
            user_checker: App\Security\UserChecker
            logout:
                path: app_logout
                target: /
            login_throttling:
                max_attempts: 9
                interval: '2 minutes'
            login_link:
                check_route: login_link
                signature_properties: [ 'id' ]
                lifetime: 1800
                max_uses: 1
            two_factor:
                auth_form_path: 2fa_login
                check_path: 2fa_login_check

            # activate different ways to authenticate
            # https://symfony.com/doc/current/security.html#the-firewall

            # https://symfony.com/doc/current/security/impersonating_user.html
            # switch_user: true

    access_control:
        - { path: ^/($|api/doc|login|oauth|reconnect-le-coffre-fort-numerique|reconnect-la-solution-pro|nous-contacter|faq-rgpd|reconnect-accompagnement-numerique|public|reinitialiser-mot-de-passe|annexe), roles: PUBLIC_ACCESS }
        - { path: ^/admin/app/user, roles: ROLE_SUPER_ADMIN }
        - { path: ^/admin, roles: ROLE_ADMIN }
        # This ensures that the form can only be accessed when two-factor authentication is in progress.
        - { path: ^/2fa, role: IS_AUTHENTICATED_2FA_IN_PROGRESS }
        - { path: ^/(.+), roles: IS_AUTHENTICATED_FULLY }


when@test:
    security:
        password_hashers:
            # By default, password hashers are resource intensive and take time. This is
            # important to generate secure password hashes. In tests however, secure hashes
            # are not important, waste resources and increase test times. The following
            # reduces the work factor to the lowest possible values.
            Symfony\Component\Security\Core\User\PasswordAuthenticatedUserInterface:
                algorithm: auto
                cost: 4 # Lowest possible value for bcrypt
                time_cost: 3 # Lowest possible value for argon
                memory_cost: 10 # Lowest possible value for argon
