files:
  - source: translations/*.yml
    translation: /translations/%two_letters_code%.yml
  - source: /translations/FosUserBundle
    translation: /translations/FosUserBundle/%two_letters_code%.yml
  - source: translations/validators
    translation: /translations/validators/%two_letters_code%.yml
bundles:
  - 4
  - 6
  - 8
