files:
  - source: translations/messages.fr.yml
    translation: /translations/message.%two_letters_code%.yml
  - source: /translations/FosUserBundle/FOSUserBundle.fr.yml
    translation: /translations/FosUserBundle/crowdin.%two_letters_code%.yml
  - source: translations/validators/validators.fr.yml
    translation: /translations/validators/crowdin.%two_letters_code%.yml
bundles:
  - 4
  - 6
  - 8
