files:
  - source: translations/*.yml
    translation: /translations/message.%two_letters_code%.yml
  - source: /translations/FosUserBundle
    translation: /translations/FosUserBundle/crowdin.%two_letters_code%.yml
  - source: translations/validators
    translation: /translations/validators/crowdin.%two_letters_code%.yml
bundles:
  - 4
  - 6
  - 8
