re_beneficiaire_accueil:
    path:     /home
    defaults: { _controller: App\Controller\BeneficiaireController::accueil }

re_beneficiaire_setQuestionSecrete:
    path:     /set-question-secrete
    defaults: { _controller: App\Controller\BeneficiaireController::setQuestionSecrete }
