<?php

namespace App\Repository;

/**
 * BeneficiaireClientRepository.
 *
 * This class was generated by the Doctrine ORM. Add your own custom
 * repository methods below.
 */
class BeneficiaireClientRepository extends \Doctrine\ORM\EntityRepository
{
}
