<?php

namespace App\Repository;

/**
 * CreatorCentreRepository.
 *
 * This class was generated by the Doctrine ORM. Add your own custom
 * repository methods below.
 */
class CreatorCentreRepository extends \Doctrine\ORM\EntityRepository
{
}
