<?php

namespace App\Repository;

/**
 * CreatorClientRepository.
 *
 * This class was generated by the Doctrine ORM. Add your own custom
 * repository methods below.
 */
class CreatorClientRepository extends \Doctrine\ORM\EntityRepository
{
}
