<?php

namespace App\Repository;

/**
 * DonneePersonnelleRepository.
 *
 * This class was generated by the Doctrine ORM. Add your own custom
 * repository methods below.
 */
class DonneePersonnelleRepository extends \Doctrine\ORM\EntityRepository
{
}
