<?php

namespace App\Repository;

use Doctrine\ORM\EntityRepository;

/**
 * DonneePersonnelleRepository.
 *
 * This class was generated by the Doctrine ORM. Add your own custom
 * repository methods below.
 */
class DonneePersonnelleRepository extends EntityRepository
{
}
