<?php

namespace App\Repository;

use Doctrine\ORM\EntityRepository;

/**
 * GestionnaireRepository.
 *
 * This class was generated by the Doctrine ORM. Add your own custom
 * repository methods below.
 */
class GestionnaireRepository extends EntityRepository
{
    public function countKPI()
    {
        $qb = $this->createQueryBuilder('g');

        $qb->select('count(g.id)')
            ->join('g.user', 'user')
            ->where('user.test = false');

        try {
            return $qb->getQuery()->getSingleScalarResult();
        } catch (\Exception $e) {
            return 0;
        }
    }
}
