<?php

namespace App\Repository;

use App\Entity\Beneficiaire;
use App\Entity\Note;
use Doctrine\Bundle\DoctrineBundle\Repository\ServiceEntityRepository;
use Doctrine\ORM\QueryBuilder;
use Doctrine\Persistence\ManagerRegistry;

/**
 * NoteRepository.
 *
 * This class was generated by the Doctrine ORM. Add your own custom
 * repository methods below.
 */
class NoteRepository extends ServiceEntityRepository
{
    public function __construct(ManagerRegistry $registry)
    {
        parent::__construct($registry, Note::class);
    }

    private function findByBeneficiaryQueryBuilder(Beneficiaire $beneficiary): QueryBuilder
    {
        return $this->createQueryBuilder('n')
            ->andWhere('n.beneficiaire = :beneficiary')
            ->setParameter('beneficiary', $beneficiary)
            ->orderBy('n.createdAt', 'DESC');
    }

    private function searchByBeneficiaryQueryBuilder(Beneficiaire $beneficiary, ?string $word): QueryBuilder
    {
        return $this->createQueryBuilder('n')
            ->andWhere('n.beneficiaire = :beneficiary')
            ->andWhere('n.nom LIKE :word OR n.contenu LIKE :word')
            ->setParameters([
                'beneficiary' => $beneficiary,
                'word' => sprintf('%%%s%%', $word),
            ])->orderBy('n.createdAt', 'DESC');
    }

    /**
     * @return Note[]
     */
    public function findAllByBeneficiary(Beneficiaire $beneficiary): array
    {
        return $this->findByBeneficiaryQueryBuilder($beneficiary)
            ->getQuery()
            ->getResult();
    }

    /**
     * @return Note[]
     */
    public function findSharedByBeneficiary(Beneficiaire $beneficiary): array
    {
        return $this->findByBeneficiaryQueryBuilder($beneficiary)
            ->andWhere('n.bPrive = FALSE')
            ->getQuery()
            ->getResult();
    }

    /**
     * @return Note[]
     */
    public function searchByBeneficiary(Beneficiaire $beneficiary, ?string $word): array
    {
        return $this->searchByBeneficiaryQueryBuilder($beneficiary, $word)
            ->getQuery()
            ->getResult();
    }

    /**
     * @return Note[]
     */
    public function searchSharedByBeneficiary(Beneficiaire $beneficiary, ?string $word): array
    {
        return $this->searchByBeneficiaryQueryBuilder($beneficiary, $word)
            ->andWhere('n.bPrive = FALSE')
            ->getQuery()
            ->getResult();
    }
}
