<?php

namespace App\Repository;

use Doctrine\ORM\EntityRepository;

/**
 * TypeCentreRepository.
 *
 * This class was generated by the Doctrine ORM. Add your own custom
 * repository methods below.
 */
class TypeCentreRepository extends EntityRepository
{
}
