<?php

return [
    'ADMIN_MAIL' => null,
    'ADMIN_MAILS' => null,
    'APP_SECRET' => null,
    'BUCKET_ACCESS_KEY' => null,
    'BUCKET_ENDPOINT' => null,
    'BUCKET_HOST' => null,
    'BUCKET_KEY' => null,
    'BUCKET_NAME' => null,
    'BUCKET_SECRET' => null,
    'BUCKET_SECRET_KEY' => null,
    'CROWDIN_DSN' => null,
    'DATABASE_URL' => null,
    'GOOGLE_SITE_VERIFICATION' => null,
    'JWT_PASSPHRASE' => null,
    'MAILER_DSN' => null,
    'MAILJET_SMS_DSN' => null,
    'MJ_APIKEY_PRIVATE' => null,
    'MJ_APIKEY_PUBLIC' => null,
    'OAUTH_ENCRYPTION_KEY' => null,
    'ROSALIE_BASIC_TOKEN' => null,
    'VONAGE_SMS_EU_DSN' => null,
    'VONAGE_SMS_US_DSN' => null,
];
