# DOCUMENT
re_app_document_list:
    path: /beneficiaire/{id}/document
    controller: App\Controller\DocumentController::index
    requirements:
        id: \d{1,10}
    options:
        expose: true

re_app_document_list_by_distant_id:
    path: /client/{clientId}/beneficiaire/{distantId}/document
    controller: App\Controller\DocumentController::listByDistantId
    requirements:
        clientId: \d{1,10}
        distantId: \d{1,10}
    options:
        expose: true

re_app_document_telecharger:
    path: /document/{id}/telecharger
    controller: App\Controller\DocumentController::telecharger
    requirements:
        id: \d{1,10}
    options:
        expose: true

# DOSSIER
re_app_dossier_telecharger:
    path: /dossier/{id}/telecharger
    controller: App\Controller\DossierController::telecharger
    requirements:
        id: \d{1,10}
    options:
        expose: true

re_app_dossier_add:
    path: /beneficiaire/{id}/dossier/ajouter
    controller: App\Controller\DossierController::add
    requirements:
        id: \d{1,10}
    methods: [ GET, POST ]
    options:
        expose: true

re_app_dossier_add_subfolder:
    path: /dossier/{id}/ajouter-sous-dossier
    controller: App\Controller\DossierController::addSubfolder
    requirements:
        id: \d{1,10}
    methods: [ GET, POST ]
    options:
        expose: true

# NOTE
re_app_note_list:
    path: /beneficiaire/{id}/note
    controller: App\Controller\NoteController::index
    methods: [ GET ]
    options:
        expose: true

re_app_note_list_by_distant_id:
    path: /client/{clientId}/beneficiaire/{distantId}/note
    controller: App\Controller\NoteController::listByDistantId
    requirements:
        clientId: \d{1,10}
        distantId: \d{1,10}

re_app_note_new:
    path: /beneficiaire/{id}/note/ajouter
    controller: App\Controller\NoteController::add
    requirements:
        id: \d{1,10}
    methods: [ GET, POST ]
    options:
        expose: true

re_app_note_edit:
    path: /note/{id}/editer
    controller: App\Controller\NoteController::edit
    requirements:
        id: \d{1,10}
    methods: [ GET, POST ]
    options:
        expose: true

# evenement
re_app_evenement_list:
    path: /beneficiaire/{id}/evenement
    controller: App\Controller\EvenementController::index
    requirements:
        id: \d{1,10}
    options:
        expose: true

re_app_evenement_list_by_distant_id:
    path: /client/{clientId}/beneficiaire/{distantId}/evenement
    controller: App\Controller\EvenementController::listByDistantId
    requirements:
        clientId: \d{1,10}
        distantId: \d{1,10}

re_app_evenement_new:
    path: /beneficiaire/{id}/evenement/ajouter
    controller: App\Controller\EvenementController::add
    options:
        expose: true

re_app_evenement_edit:
    path: /evenement/{id}/editer
    controller: App\Controller\EvenementController::edit
    requirements:
        id: \d{1,10}
    options:
        expose: true

# CONTACT
re_app_contact_list:
    path: /beneficiaire/{id}/contact
    controller: App\Controller\ContactController::index
    requirements:
        id: \d{1,10}
    methods: [ GET ]
    options:
        expose: true

re_app_contact_list_by_distant_id:
    path: /client/{clientId}/beneficiaire/{distantId}/contact
    controller: App\Controller\ContactController::listByDistantId
    requirements:
        clientId: \d{1,10}
        distantId: \d{1,10}

re_app_contact_add:
    path: /beneficiaire/{id}/contact/ajouter
    controller: App\Controller\ContactController::add
    requirements:
        id: \d{1,10}
    methods: [ GET, POST ]
    options:
        expose: true

re_app_contact_edit:
    path: /contact/{id}/editer
    controller: App\Controller\ContactController::edit
    requirements:
        id: \d{1,10}
    methods: [ GET, POST ]
    options:
        expose: true

