oauth2:
    resource: '@LeagueOAuth2ServerBundle/Resources/config/routes.php'
    type: php
    prefix: /api

controllers:
    type: attribute
    resource: '../src/Controller/'

#Controllers V2
controllers_v2:
    type: attribute
    resource: '../src/ControllerV2/'
