re.api_rest:
    type: attribute
    resource: App\Controller\Rest\APIRestController

##### API REST V2 #####
api_v2_beneficiaire:
    type: attribute
    resource: App\Controller\Rest\BeneficiaireRestV2Controller

api_v2_centre:
    type: attribute
    resource: App\Controller\Rest\CentreRestV2Controller

api_v2_contact:
    type: attribute
    resource: App\Controller\Rest\ContactRestV2Controller

api_v2_document:
    type: attribute
    resource: App\Controller\Rest\DocumentRestV2Controller

api_v2_dossier:
    type: attribute
    resource: App\Controller\Rest\DossierRestV2Controller

api_v2_evenement:
    type: attribute
    resource: App\Controller\Rest\EvenementRestV2Controller

api_v2_membre:
    type: attribute
    resource: App\Controller\Rest\MembreRestV2Controller

api_v2_note:
    type: attribute
    resource: App\Controller\Rest\NoteRestV2Controller

api_v2_user:
    type: attribute
    resource: App\Controller\Rest\UserRestV2Controller

re_rest_public:
    type: attribute
    resource: App\Controller\Rest\PublicRestController

api_v3_document:
    type: attribute
    resource: App\Controller\Api\DocumentApiController

api_v3_beneficiary:
    type: attribute
    resource: App\Controller\Api\BeneficiaryApiController

oauth2:
    resource: '@LeagueOAuth2ServerBundle/Resources/config/routes.php'
    type: php
    prefix: /api

controllers:
    type: attribute
    resource: '../src/Controller/'

#Controllers V2
controllers_v2:
    type: attribute
    resource: '../src/ControllerV2/'
