App\Entity\CreatorCentre:
  type: entity
  table: null
  repositoryClass: App\Repository\CreatorCentreRepository
  manyToOne:
    entity:
      targetEntity: App\Entity\Attributes\Centre
  lifecycleCallbacks: {  }
