App\Entity\Gestionnaire:
    type: entity
    table: "gestionnaire"
    repositoryClass: App\Repository\GestionnaireRepository
    id:
        id:
            type: integer
            id: true
            generator:
                strategy: AUTO
    fields:
        createdAt:
            type: datetime
            column: createdAt
            gedmo:
                timestampable:
                    on: create
        updatedAt:
            type: datetime
            column: updatedAt
            gedmo:
                timestampable:
                    on: update
    oneToOne:
        user:
            targetEntity: App\Entity\User
            cascade: [ 'persist','remove' ]
            inversedBy: subjectGestionnaire
            joinColumn:
                nullable: false
    oneToMany:
        centres:
            targetEntity: App\Entity\Attributes\Centre
            mappedBy: gestionnaire
        externalLinks:
            targetEntity: App\Entity\ClientGestionnaire
            mappedBy: entity
            orphanRemoval: true
    manyToOne:
        association:
            targetEntity: App\Entity\Association
            inversedBy: gestionnaires
            joinColumn:
                nullable: false
    lifecycleCallbacks: { }
