name: Symfony

on:
    push:
        branches: [ "main", "dev", "release/**" ]
    pull_request:
        branches: [ "main", "dev", "release/**" ]

permissions:
    contents: read

jobs:
    symfony-tests:
        runs-on: ubuntu-latest

        services:
            mariadb:
                image: mariadb:latest
                env:
                    MYSQL_ROOT_PASSWORD: Pl1PL6axxvOR9eY2
                    MYSQL_DATABASE: vault_test
                    MYSQL_USER: vault
                    MYSQL_PASSWORD: Pl1PL6axxvOR9eY2
                ports:
                    - 3306:3306
                options: >-
                    --health-cmd="mariadb-admin ping -h localhost"
                    --health-interval=10s
                    --health-timeout=5s
                    --health-retries=10

        strategy:
            matrix:
                php-versions:
                  [ "8.3" ]
        name: PHP ${{ matrix.php-versions }} Test on ubuntu-latest
        steps:
            # —— Backend setup 🔧 ——————————————————————————————————————————————————
            -   uses: shivammathur/setup-php@v2
                with:
                    php-version: ${{ matrix.php-versions }}
            -   uses: actions/checkout@v3
            -   name: Cache Composer packages
                id: composer-cache
                uses: actions/cache@v3
                with:
                    path: vendor
                    key: ${{ runner.os }}-php-${{ hashFiles('**/composer.lock') }}
                    restore-keys: |
                        ${{ runner.os }}-php-
            -   name: Verify MariaDB connection
                run: |
                    while ! mysqladmin ping -h"127.0.0.1" --silent; do
                    sleep 1
                    done
            -   name: Merge default env vars and CI vars
                run: cat .env.ci >> .env.test
            -   name: Install Dependencies
                run: composer install -q --no-ansi --no-interaction --no-scripts --no-progress --prefer-dist
#            -   name: Composer audit
#                run: composer audit
            # —— Check coding standards ✨ ————————————————————————————————————————————————————————————————
            -   name: Check CS
                run: vendor/bin/php-cs-fixer fix src -v --dry-run --stop-on-violation --using-cache=no
            -   name: Check Rector
                run: vendor/bin/rector process --dry-run
            -   name: Dump routes
                run: php bin/console fos:js-routing:dump --format=json --target=public/js/fos_js_routes.json
            -   name: Copy keys
                run: mkdir -p var/oauth && cp tests/keys/* var/oauth
            -   name: Run Doctrine Migrations
                run: php bin/console doctrine:migrations:migrate -n --env=test
            # —— Setup frontend 💄 ——————————————————————————————————————————————————————————————————————
            -   name: Install and build frontend
                run: yarn && yarn dev
            # —— Check frontend dependencies 🔒️ —————————————————————————————————————————————————————————
#            -   name: Make script executable
#                run: chmod +x ./yarn-security-checker.sh
#            -   name: Check dependencies security issues
#                run: ./yarn-security-checker.sh
            # —— Run tests ✅ ———————————————————————————————————————————————————————————————————————————
            -   name: Load v1 fixtures
                run: php bin/console doctrine:fixtures:load --env=test --group=v1 -n
            -   name: Run v1 tests
                run: ./vendor/bin/simple-phpunit tests/v1
            -   name: Load v2 fixtures
                run: php bin/console doctrine:fixtures:load --env=test --group=v2 -n
            -   name: Run v2 tests
                run: ./vendor/bin/simple-phpunit tests/v2
            # —— Code static analysis ✨ ——————————————————————————————————————————————————
            -   name: Static code analysis
                run: vendor/bin/phpstan analyse -c phpstan.dist.neon
