name: Symfony

on:
    push:
        branches: [ "main" ]
    pull_request:
        branches: [ "main" ]

permissions:
    contents: read

jobs:
    symfony-tests:
        runs-on: ubuntu-latest
        steps:
            - uses: shivammathur/setup-php@2cb9b829437ee246e9b3cac53555a39208ca6d28
              with:
                  php-version: '8.2'
            - uses: actions/checkout@v3
            - name: Cache Composer packages
              id: composer-cache
              uses: actions/cache@v3
              with:
                  path: vendor
                  key: ${{ runner.os }}-php-${{ hashFiles('**/composer.lock') }}
                  restore-keys: |
                      ${{ runner.os }}-php-
            - name: Start MariaDB
              # You may pin to the exact commit or the version.
              # uses: getong/mariadb-action@acf7bc08e06a9c26e2a534d54284cb9a62697e7d
              uses: getong/mariadb-action@v1.1
              with:
                # The port of host
                # MYSQL_ROOT_PASSWORD - root superuser password
                mysql root password: vault
                # MYSQL_DATABASE - name for the default database that is created
                mysql database: vault_test
                # MYSQL_USER - create the specified user with superuser power for created database
                mysql user: vault
                # MYSQL_PASSWORD - specified superuser password which user is power for created database
                mysql password: vault
            - name: Install Dependencies
              run: composer install -q --no-ansi --no-interaction --no-scripts --no-progress --prefer-dist
            - name: Run Doctrine Migrations
              run: php bin/console debug:dotenv --env=test
            - name: Run Doctrine Migrations
              run: php bin/console doctrine:migrations:migrate -n --env=test
